project_id = "jobopjhhxgcfanlhzlkc"

[functions.sync-entra-id]
verify_jwt = false

[functions.sync-csv-colab]
verify_jwt = false

[functions.sync-sharepoint-csv]
verify_jwt = false

[functions.execute-rules]
verify_jwt = false