project_id = "jobopjhhxgcfanlhzlkc"


[functions.sync-csv-colab]
verify_jwt = false

[functions.sync-sharepoint-csv]
verify_jwt = false

[functions.execute-rules]
verify_jwt = false

[functions.iam-agent-api]
verify_jwt = false

