// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-colaboradores.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_colaboradores_default = defineTool({
  name: "list_colaboradores",
  title: "Listar colaboradores",
  description: "Lista colaboradores do \xD3rigo Access & Identity. Suporta filtros por status, empresa, \xE1rea, cargo, busca por nome/email e pagina\xE7\xE3o.",
  inputSchema: {
    search: z.string().optional().describe("Filtro por nome ou email (ilike)."),
    status: z.string().optional().describe("Status do colaborador (ex.: ativo, desligado, inativo)."),
    empresa_id: z.string().uuid().optional(),
    area_id: z.string().uuid().optional(),
    cargo_id: z.string().uuid().optional(),
    limit: z.number().int().min(1).max(200).optional().describe("Padr\xE3o 50, m\xE1ximo 200."),
    offset: z.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb(ctx).from("colaboradores").select("id,nome,email,status,cargo_id,area_id,empresa_id,entra_id,data_admissao,data_desligamento,employ_id", { count: "exact" }).range(offset, offset + limit - 1).order("nome");
    if (input.search) q = q.or(`nome.ilike.%${input.search}%,email.ilike.%${input.search}%`);
    if (input.status) q = q.eq("status", input.status);
    if (input.empresa_id) q = q.eq("empresa_id", input.empresa_id);
    if (input.area_id) q = q.eq("area_id", input.area_id);
    if (input.cargo_id) q = q.eq("cargo_id", input.cargo_id);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, returned: data?.length ?? 0, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/tools/get-colaborador.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_colaborador_default = defineTool2({
  name: "get_colaborador",
  title: "Detalhes do colaborador",
  description: "Retorna detalhes completos de um colaborador (por id, email ou employ_id), incluindo perfis atribu\xEDdos, \xFAltimos eventos JML e itens abertos na fila IAM.",
  inputSchema: {
    id: z2.string().uuid().optional(),
    email: z2.string().email().optional(),
    employ_id: z2.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const client = sb2(ctx);
    let q = client.from("colaboradores").select("*").limit(1);
    if (input.id) q = q.eq("id", input.id);
    else if (input.email) q = q.eq("email", input.email);
    else if (input.employ_id) q = q.eq("employ_id", input.employ_id);
    else return { content: [{ type: "text", text: "Informe id, email ou employ_id." }], isError: true };
    const { data: colab, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!colab) return { content: [{ type: "text", text: "Colaborador n\xE3o encontrado." }], isError: true };
    const [{ data: perfis }, { data: eventos }, { data: fila }] = await Promise.all([
      client.from("perfil_atribuicoes").select("*").eq("colaborador_id", colab.id),
      client.from("eventos_jml").select("*").eq("colaborador_id", colab.id).order("created_at", { ascending: false }).limit(10),
      client.from("iam_queue").select("*").eq("colaborador_id", colab.id).in("status", ["pending", "waiting_approval", "processing"]).order("created_at", { ascending: false }).limit(50)
    ]);
    return {
      content: [{ type: "text", text: JSON.stringify({ colaborador: colab, perfis, eventos_jml: eventos, iam_queue_abertos: fila }) }],
      structuredContent: { colaborador: colab, perfis, eventos_jml: eventos, iam_queue_abertos: fila }
    };
  }
});

// src/lib/mcp/tools/list-terceiros.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_terceiros_default = defineTool3({
  name: "list_terceiros",
  title: "Listar terceiros",
  description: "Lista terceiros com filtros por status, empresa e busca por nome/email.",
  inputSchema: {
    search: z3.string().optional(),
    status: z3.string().optional(),
    empresa_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).optional(),
    offset: z3.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb3(ctx).from("terceiros").select("*", { count: "exact" }).order("nome").range(offset, offset + limit - 1);
    if (input.search) q = q.or(`nome.ilike.%${input.search}%,email.ilike.%${input.search}%`);
    if (input.status) q = q.eq("status", input.status);
    if (input.empresa_id) q = q.eq("empresa_id", input.empresa_id);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/tools/list-iam-queue.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_iam_queue_default = defineTool4({
  name: "list_iam_queue",
  title: "Listar fila IAM",
  description: "Lista itens da fila IAM (provisionamento/revoga\xE7\xE3o). Filtra por status, tipo de a\xE7\xE3o, requester e colaborador.",
  inputSchema: {
    status: z4.array(z4.string()).optional().describe("Ex.: ['pending','waiting_approval','processing','success','failed','cancelled']"),
    action_type: z4.string().optional(),
    requested_by: z4.string().optional(),
    colaborador_id: z4.string().uuid().optional(),
    limit: z4.number().int().min(1).max(200).optional(),
    offset: z4.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb4(ctx).from("iam_queue").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (input.status?.length) q = q.in("status", input.status);
    if (input.action_type) q = q.eq("action_type", input.action_type);
    if (input.requested_by) q = q.eq("requested_by", input.requested_by);
    if (input.colaborador_id) q = q.eq("colaborador_id", input.colaborador_id);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/tools/approve-iam-item.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var approve_iam_item_default = defineTool5({
  name: "approve_iam_item",
  title: "Aprovar item da fila IAM",
  description: "Aprova (libera para execu\xE7\xE3o) ou cancela um item da fila IAM. Tamb\xE9m aceita motivo opcional para auditoria.",
  inputSchema: {
    item_id: z5.string().uuid(),
    decision: z5.enum(["approve", "cancel"]),
    reason: z5.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ item_id, decision, reason }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const client = sb5(ctx);
    const newStatus = decision === "approve" ? "pending" : "cancelled";
    const patch = {
      status: newStatus,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (reason) patch.last_error = reason;
    const { data, error } = await client.from("iam_queue").update(patch).eq("id", item_id).in("status", ["waiting_approval", "pending"]).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Item n\xE3o encontrado ou n\xE3o eleg\xEDvel." }], isError: true };
    await client.from("auditoria").insert({
      acao: decision === "approve" ? "aprovar_iam_item" : "cancelar_iam_item",
      entidade: "iam_queue",
      resumo: `Item ${item_id} ${decision === "approve" ? "aprovado" : "cancelado"} via MCP (Hermes agent)`,
      operador: ctx.getUserEmail() ?? "hermes-agent",
      detalhes: { item_id, decision, reason }
    });
    return {
      content: [{ type: "text", text: JSON.stringify({ ok: true, item: data }) }],
      structuredContent: { ok: true, item: data }
    };
  }
});

// src/lib/mcp/tools/start-jml-event.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var start_jml_event_default = defineTool6({
  name: "start_jml_event",
  title: "Iniciar evento JML",
  description: "Inicia um evento JML (Joiner/Mover/Leaver/Pr\xE9-Leaver) para um colaborador. Chama a Edge Function start-jml-event, respeitando as regras internas.",
  inputSchema: {
    tipo: z6.enum(["joiner", "mover", "leaver", "pre_leaver"]),
    colaboradorId: z6.string().uuid().nullable().optional(),
    colaboradorNome: z6.string(),
    motivo: z6.string().min(3)
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const url = `${globalThis.process.env.SUPABASE_URL}/functions/v1/start-jml-event`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`,
        apikey: globalThis.process.env.SUPABASE_PUBLISHABLE_KEY
      },
      body: JSON.stringify({ ...input, origem: "mcp_hermes" })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || body?.error) {
      return { content: [{ type: "text", text: JSON.stringify(body) }], isError: true };
    }
    await sb6(ctx).from("auditoria").insert({
      acao: "iniciar_evento_jml",
      entidade: "eventos_jml",
      resumo: `Evento JML ${input.tipo} iniciado via MCP (Hermes) para ${input.colaboradorNome}`,
      operador: ctx.getUserEmail() ?? "hermes-agent",
      detalhes: { input, response: body }
    });
    return {
      content: [{ type: "text", text: JSON.stringify(body) }],
      structuredContent: body
    };
  }
});

// src/lib/mcp/tools/list-eventos-jml.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^4.4.3";
function sb7(ctx) {
  return createClient7(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_eventos_jml_default = defineTool7({
  name: "list_eventos_jml",
  title: "Listar eventos JML",
  description: "Lista eventos JML (Joiner/Mover/Leaver/Pr\xE9-Leaver) com filtros de tipo, status e colaborador.",
  inputSchema: {
    tipo: z7.string().optional(),
    status: z7.string().optional(),
    colaborador_id: z7.string().uuid().optional(),
    limit: z7.number().int().min(1).max(200).optional(),
    offset: z7.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb7(ctx).from("eventos_jml").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (input.tipo) q = q.eq("tipo", input.tipo);
    if (input.status) q = q.eq("status", input.status);
    if (input.colaborador_id) q = q.eq("colaborador_id", input.colaborador_id);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/tools/list-auditoria.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^4.4.3";
function sb8(ctx) {
  return createClient8(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_auditoria_default = defineTool8({
  name: "list_auditoria",
  title: "Consultar auditoria",
  description: "Consulta o log de auditoria com filtros por a\xE7\xE3o, entidade, operador e intervalo de datas.",
  inputSchema: {
    acao: z8.string().optional(),
    entidade: z8.string().optional(),
    operador: z8.string().optional(),
    since: z8.string().optional().describe("ISO date, ex.: 2026-06-01"),
    until: z8.string().optional(),
    limit: z8.number().int().min(1).max(200).optional(),
    offset: z8.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb8(ctx).from("auditoria").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (input.acao) q = q.eq("acao", input.acao);
    if (input.entidade) q = q.eq("entidade", input.entidade);
    if (input.operador) q = q.eq("operador", input.operador);
    if (input.since) q = q.gte("created_at", input.since);
    if (input.until) q = q.lte("created_at", input.until);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/tools/list-alertas.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^4.4.3";
function sb9(ctx) {
  return createClient9(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_alertas_default = defineTool9({
  name: "list_alertas",
  title: "Listar alertas",
  description: "Lista alertas do sistema com filtros por severidade e status (lido/n\xE3o lido).",
  inputSchema: {
    severidade: z9.string().optional(),
    lido: z9.boolean().optional(),
    limit: z9.number().int().min(1).max(200).optional(),
    offset: z9.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const limit = input.limit ?? 50;
    const offset = input.offset ?? 0;
    let q = sb9(ctx).from("alertas").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (input.severidade) q = q.eq("severidade", input.severidade);
    if (typeof input.lido === "boolean") q = q.eq("lido", input.lido);
    const { data, error, count } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: count, items: data }) }],
      structuredContent: { total: count, items: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jobopjhhxgcfanlhzlkc";
var mcp_default = defineMcp({
  name: "origo-access-identity-mcp",
  title: "\xD3rigo Access & Identity",
  version: "0.1.0",
  instructions: "Servidor MCP do \xD3rigo Access & Identity (IGA para JML da \xD3rigo Energia). Ferramentas permitem consultar colaboradores, terceiros, eventos JML, fila IAM, auditoria e alertas; iniciar eventos JML; aprovar/cancelar itens da fila IAM. Todas as a\xE7\xF5es executam como o usu\xE1rio autenticado via OAuth e respeitam RLS/p\xE1peis. Prefira sempre buscar contexto antes de agir e registre motivo claro em a\xE7\xF5es destrutivas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_colaboradores_default,
    get_colaborador_default,
    list_terceiros_default,
    list_iam_queue_default,
    approve_iam_item_default,
    start_jml_event_default,
    list_eventos_jml_default,
    list_auditoria_default,
    list_alertas_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
